<?php
return [
    [
        'title'=>'test',
        'href'=>'/Product',
        'img'=>'/Global/Style/Home/images/fc_product_img.png'
    ],
    [
        'title'=>'test',
        'href'=>'/Product',
        'img'=>'/Global/Style/Home/images/fc_product_img.png'
    ],
    [
        'title'=>'test',
        'href'=>'/Product',
        'img'=>'/Global/Style/Home/images/fc_product_img.png'
    ],
    [
        'title'=>'test',
        'href'=>'/Product',
        'img'=>'/Global/Style/Home/images/fc_product_img.png'
    ],
    [
        'title'=>'test',
        'href'=>'/Product',
        'img'=>'/Global/Style/Home/images/fc_product_img.png'
    ]
];
