<?php
/**
 *
 * 路由设置
 */
return [
    //admin 后台
    [
        'method'=>'GET',
        'rule'=>'/Admin',
        'controller'=>[
            'Admin\Controller\IndexController',
            'index'
        ]
    ],
    //news
    [
        'method'=>'GET',
        'rule'=>'/Admin/News',
        'controller'=>[
            'Admin\Controller\NewsController',
            'index'
        ]
    ],
    [
        'method'=>'GET',
        'rule'=>'/Admin/News/{newsId:\d+}',
        'controller'=>[
            'Admin\Controller\NewsController',
            'get'
        ]
    ],
    [
        'method'=>'GET',
        'rule'=>'/Admin/News/Save[/{newsId:\d+}]',
        'controller'=>[
            'Admin\Controller\NewsController',
            'save'
        ]
    ],
    [
        'method'=>'POST',
        'rule'=>'/Admin/News/Save[/{newsId:\d+}]',
        'controller'=>[
            'Admin\Controller\NewsController',
            'action'
        ]
    ],
    [
        'method'=>'GET',
        'rule'=>'/Admin/News/Delete/{newsId:\d+}',
        'controller'=>[
            'Admin\Controller\NewsController',
            'delete'
        ]
    ],
    //inquiry
    [
        'method'=>'GET',
        'rule'=>'/Admin/Inquiry',
        'controller'=>[
            'Admin\Controller\InquiryController',
            'index'
        ]
    ],
    [
        'method'=>'GET',
        'rule'=>'/Admin/Inquiry/{inquiryId:\d+}',
        'controller'=>[
            'Admin\Controller\InquiryController',
            'get'
        ]
    ],
    //brand
    [
        'method'=>'GET',
        'rule'=>'/Admin/Brand',
        'controller'=>[
            'Admin\Controller\BrandController',
            'index'
        ]
    ],
    [
        'method'=>'GET',
        'rule'=>'/Admin/Brand/{brandId:\d+}',
        'controller'=>[
            'Admin\Controller\BrandController',
            'get'
        ]
    ],
    [
        'method'=>'GET',
        'rule'=>'/Admin/Brand/Save[/{brandId:\d+}]',
        'controller'=>[
            'Admin\Controller\BrandController',
            'save'
        ]
    ],
    [
        'method'=>'POST',
        'rule'=>'/Admin/Brand/Save[/{brandId:\d+}]',
        'controller'=>[
            'Admin\Controller\BrandController',
            'action'
        ]
    ],
    [
        'method'=>'GET',
        'rule'=>'/Admin/Brand/Delete/{brandId:\d+}',
        'controller'=>[
            'Admin\Controller\BrandController',
            'delete'
        ]
    ],
    //Category
    [
        'method'=>'GET',
        'rule'=>'/Admin/Category',
        'controller'=>[
            'Admin\Controller\CategoryController',
            'index'
        ]
    ],
    [
        'method'=>'GET',
        'rule'=>'/Admin/Category/{categoryId:\d+}',
        'controller'=>[
            'Admin\Controller\CategoryController',
            'get'
        ]
    ],
    [
        'method'=>'GET',
        'rule'=>'/Admin/Category/Save[/{categoryId:\d+}]',
        'controller'=>[
            'Admin\Controller\CategoryController',
            'save'
        ]
    ],
    [
        'method'=>'POST',
        'rule'=>'/Admin/Category/Save[/{categoryId:\d+}]',
        'controller'=>[
            'Admin\Controller\CategoryController',
            'action'
        ]
    ],
    //Product
    [
        'method'=>'GET',
        'rule'=>'/Admin/Product',
        'controller'=>[
            'Admin\Controller\ProductController',
            'index'
        ]
    ],
    [
        'method'=>'GET',
        'rule'=>'/Admin/Product/{productId:\d+}',
        'controller'=>[
            'Admin\Controller\ProductController',
            'get'
        ]
    ],
    [
        'method'=>'POST',
        'rule'=>'/Admin/Product/Save[/{productId:\d+}]',
        'controller'=>[
            'Admin\Controller\ProductController',
            'save'
        ]
    ],
    [
        'method'=>'GET',
        'rule'=>'/Admin/Product/Delete/{productId:\d+}',
        'controller'=>[
            'Admin\Controller\ProductController',
            'delete'
        ]
    ],
];
