<?php
/**
 *
 * 路由设置
 */
return [
    //admin 后台
    [
        'method'=>'GET',
        'rule'=>'/Admin',
        'controller'=>[
            'Admin\Controller\IndexController',
            'index'
        ]
    ],
    //news
    [
        'method'=>'GET',
        'rule'=>'/Admin/News',
        'controller'=>[
            'Admin\Controller\NewsController',
            'index'
        ]
    ],
    [
        'method'=>'GET',
        'rule'=>'/Admin/News/{newsId:\d+}',
        'controller'=>[
            'Admin\Controller\NewsController',
            'get'
        ]
    ],
    [
        'method'=>'GET',
        'rule'=>'/Admin/News/Save[/{newsId:\d+}]',
        'controller'=>[
            'Admin\Controller\NewsController',
            'save'
        ]
    ],
    [
        'method'=>'POST',
        'rule'=>'/Admin/News/Save[/{newsId:\d+}]',
        'controller'=>[
            'Admin\Controller\NewsController',
            'action'
        ]
    ],
    [
        'method'=>'GET',
        'rule'=>'/Admin/News/Delete/{newsId:\d+}',
        'controller'=>[
            'Admin\Controller\NewsController',
            'delete'
        ]
    ],
    //inquiry
    [
        'method'=>'GET',
        'rule'=>'/Admin/Inquiry',
        'controller'=>[
            'Admin\Controller\InquiryController',
            'index'
        ]
    ],
    [
        'method'=>'GET',
        'rule'=>'/Admin/Inquiry/{inquiryId:\d+}',
        'controller'=>[
            'Admin\Controller\InquiryController',
            'get'
        ]
    ],
    //brand
    [
        'method'=>'GET',
        'rule'=>'/Admin/Brand',
        'controller'=>[
            'Admin\Controller\BrandController',
            'index'
        ]
    ],
    [
        'method'=>'GET',
        'rule'=>'/Admin/Brand/{brandId:\d+}',
        'controller'=>[
            'Admin\Controller\BrandController',
            'get'
        ]
    ],
    [
        'method'=>'GET',
        'rule'=>'/Admin/Brand/Save[/{brandId:\d+}]',
        'controller'=>[
            'Admin\Controller\BrandController',
            'save'
        ]
    ],
    [
        'method'=>'POST',
        'rule'=>'/Admin/Brand/Save[/{brandId:\d+}]',
        'controller'=>[
            'Admin\Controller\BrandController',
            'action'
        ]
    ],
    [
        'method'=>'GET',
        'rule'=>'/Admin/Brand/Delete/{brandId:\d+}',
        'controller'=>[
            'Admin\Controller\BrandController',
            'delete'
        ]
    ],
    //Category
    [
        'method'=>'GET',
        'rule'=>'/Admin/Category',
        'controller'=>[
            'Admin\Controller\CategoryController',
            'index'
        ]
    ],
    [
        'method'=>'GET',
        'rule'=>'/Admin/Category/Save[/{categoryId:\d+}]',
        'controller'=>[
            'Admin\Controller\CategoryController',
            'save'
        ]
    ],
    [
        'method'=>'POST',
        'rule'=>'/Admin/Category/Save[/{categoryId:\d+}]',
        'controller'=>[
            'Admin\Controller\CategoryController',
            'action'
        ]
    ],
    //Product
    [
        'method'=>'GET',
        'rule'=>'/Admin/Product',
        'controller'=>[
            'Admin\Controller\ProductController',
            'index'
        ]
    ],
    [
        'method'=>'GET',
        'rule'=>'/Admin/Product/{productId:\d+}',
        'controller'=>[
            'Admin\Controller\ProductController',
            'get'
        ]
    ],
    [
        'method'=>'GET',
        'rule'=>'/Admin/Product/Save[/{productId:\d+}]',
        'controller'=>[
            'Admin\Controller\ProductController',
            'save'
        ]
    ],
    [
        'method'=>'POST',
        'rule'=>'/Admin/Product/Save[/{productId:\d+}]',
        'controller'=>[
            'Admin\Controller\ProductController',
            'action'
        ]
    ],
    [
        'method'=>'GET',
        'rule'=>'/Admin/Product/Delete/{productId:\d+}',
        'controller'=>[
            'Admin\Controller\ProductController',
            'delete'
        ]
    ],
    //productSlide
    [
        'method'=>'GET',
        'rule'=>'/Admin/Product/{productId:\d+}/Slides',
        'controller'=>[
            'Admin\Controller\ProductController',
            'slides'
        ]
    ],
    [
        'method'=>'GET',
        'rule'=>'/Admin/Product/{productId:\d+}/Slides/Save',
        'controller'=>[
            'Admin\Controller\ProductController',
            'slidesSave'
        ]
    ],
    [
        'method'=>'POST',
        'rule'=>'/Admin/Product/{productId:\d+}/Slides/Save',
        'controller'=>[
            'Admin\Controller\ProductController',
            'slidesAction'
        ]
    ],
    [
        'method'=>'GET',
        'rule'=>'/Admin/Product/{productId:\d+}/Slides/{fileId:\d+}/Delete',
        'controller'=>[
            'Admin\Controller\ProductController',
            'slidesDelete'
        ]
    ],
    //Home 前台
     [
        'method'=>'GET',
        'rule'=>'/About',
        'controller'=>[
            'Home\Controller\IndexController',
            'about'
        ]
     ],
    [
        'method'=>'GET',
        'rule'=>'/Contacts',
        'controller'=>[
            'Home\Controller\IndexController',
            'contacts'
        ]
    ],
    //inquiry
    [
        'method'=>'GET',
        'rule'=>'/Inquiry[/Product/{productId:\d+}]',
        'controller'=>[
            'Inquiry\Controller\IndexController',
            'index'
        ]
    ],
    [
        'method'=>'GET',
        'rule'=>'/Inquiry/Success',
        'controller'=>[
            'Inquiry\Controller\IndexController',
            'success'
        ]
    ],
    [
        'method'=>'POST',
        'rule'=>'/Inquiry[/Product/{productId:\d+}]',
        'controller'=>[
            'Inquiry\Controller\IndexController',
            'action'
        ]
    ],
    //news
    [
        'method'=>'GET',
        'rule'=>'/News',
        'controller'=>[
            'News\Controller\IndexController',
            'index'
        ]
    ],
    [
        'method'=>'GET',
        'rule'=>'/News/{newsId:\d+}',
        'controller'=>[
            'News\Controller\IndexController',
            'get'
        ]
    ],
    //product
    [
        'method'=>'GET',
        'rule'=>'/Product',
        'controller'=>[
            'Product\Controller\IndexController',
            'index'
        ]
    ],
    [
        'method'=>'GET',
        'rule'=>'/Product/{productId:\d+}',
        'controller'=>[
            'Product\Controller\IndexController',
            'get'
        ]
    ],
];
